### ISSUE TITLE
Email Notifications plugin not working

### ISSUE THREAD

**Issue by aristosv** [jellyfin/jellyfin-plugin-emailnotifications#11]
On jellyfin Version: 10.5.2 on docker, I installed email notifications v4.0

I have a gmail account I use for all notifications (sonarr, radarr, bazarr, etc..)

It just doesn't seem to work with the email notifications plugin on jellyfin though.

Email from: my gmail email address
Email to: my personal email address
SMTP hostname: smtp.gmail.com
SMTP port: 587
Enable SSL / TLS
Enable SMTP Authentication
SMTP username: my gmail email address
SMTP password: my gmail password

This is the error I get when I click on the "Test Notification" button.

![1](https://user-images.githubusercontent.com/528302/78507032-71fdc180-7786-11ea-90e1-eee0d4a31101.png)

These are the relevant logs in the jellyfin log file

```
[2020-04-05 21:39:46.808 +03:00] [ERR] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.MissingMethodException: Method not found: 'MediaBrowser.Controller.Entities.User MediaBrowser.Controller.Library.IUserManager.GetUserById(System.String)'.
   at MediaBrowser.Plugins.SmtpNotifications.Api.ServerApiEndpoints.Post(TestNotification request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by HanFox** [comment]
The issue with the Test notification was fixed by myself a few days ago [here](https://github.com/jellyfin/jellyfin-plugin-emailnotifications/commit/da7316b30ef32f7398357a87eaa6cb306ebbc274), however, I have noticed that the plugin doesn't actually seem to even try to send any other notifications, so I guess my fix is a bit moot and quite possibly why no new release has actually been done.

If I can find more time I'll look at trying to fix it all properly and maybe it'll get a release then, but again that may be a waste of time as the System.Net.Mail class that this plugin uses has been obsoleted, and a modern app like Jellyfin should probably look at moving away from it.

Probably a tad off-topic, but it's recommended to use [MailKit](https://github.com/jstedfast/MailKit) ([DE0005: SmtpClient shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md)), but fully re-writing this plugin may be beyond me. I don't really code in C#.

**Comment by Protektor-Desura** [comment]
In Jellyfin 10.6.0 I am getting this error.


[08:27:12] [INF] [14] MediaBrowser.Plugins.SmtpNotifications.Notifier: Sending email xxxxx@gmail.com with subject Jellyfin: Jellyfin Server needs to be restarted
[08:27:12] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[08:27:22] [ERR] [32] MediaBrowser.Plugins.SmtpNotifications.Notifier: Error sending email
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at MediaBrowser.Plugins.SmtpNotifications.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
[08:27:22] [ERR] [20] MediaBrowser.Plugins.SmtpNotifications.Notifier: Error sending email
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at MediaBrowser.Plugins.SmtpNotifications.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
