### ISSUE TITLE
Jelly master and email stable/unstable not working

### ISSUE THREAD

**Issue by rayures** [jellyfin/jellyfin-plugin-emailnotifications#20]
Jellyfin master ( 2021-01-24)
Email notification version: 9.2101.2419.3813

also does not work with v9.0.0.0

getting this error in the jelly log when pressing 'test notification' and when jelly tried to send an email based on notification settings.
````

[21:45:13] [DBG] [4] Emby.Notifications.NotificationManager: Sending notification via Email Notifications to user XXX
[21:45:14] [ERR] [4] Emby.Notifications.NotificationManager: Error sending notification to Email Notifications
MimeKit.ParseException: Unexpected token at offset 26
   at MimeKit.MailboxAddress.set_Address(String value)
   at MimeKit.MailboxAddress..ctor(Encoding encoding, String name, String address)
   at MimeKit.MailboxAddress..ctor(String name, String address)
   at MediaBrowser.Plugins.SmtpNotifications.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
   at Emby.Notifications.NotificationManager.SendNotification(NotificationRequest request, INotificationService service, String title, String description, User user, CancellationToken cancellationToken)
````

**Comment by crobibero** [comment]
This looks like configuration error, can you double check what was entered in the email address fields?

**Comment by rayures** [comment]
hi, 

email field has user@fqdn, nothing fancy. 
i also run an 10.5.5 instance, with the same settings that works fine (just copy pasted them to this master installation). 

//edit
took the hard way to fix it:
exported 10.5.5 instance settings and imported them into master instance. works. No idea what was wrong.
